### ISSUE TITLE
Make element sticky

### ISSUE THREAD

**Issue by erichaus** [rwjblue/ember-waypoints#9]
Hello,

I came across this and looking to make an element stick to top on scroll, is there anyway to use this with the sticky.js that I see in the docs or would I have to do that separately?

Thanks!

http://imakewebthings.com/waypoints/shortcuts/sticky-elements/

**Comment by danlourenco** [comment]
+1

**Comment by KirillSuhodolov** [comment]
+1

**Comment by Kimberlyge** [comment]
+1
